export const Order = {
  child: (index) => `:nth-child(${index}) > label > .patrat`,

  notifyTitle: ".notify__title",
  text: "Produsul a fost adăugat în coș",
  openCart: "#openCartModalBtn > .fas",
  firstItem: "#heading-pb1 > .mb-0",
  gender: "#gender",
  fetita: "fetita",
  blond: "blond",
  negri: "negri",
  testName: "test",
  hairColor: "#hairColor",
  eyeColor: "#eyeColor",
  childrenName: "#childrenName",
  childrenSurname: "#childrenSurname",
  next: "#withContactsNextBtn",
  back: "#backToPreviewPageBtn",
  contactName: "#contactName",
  name: "test test1",
  contactAddress: "#address",
  address: "123 test",
  contactPhone: "#phone",
  phone: "123 456 789",
  continue: "#buyPersonalizedItemBtn",
  comandButton: ".swal2-confirm",
};
